# 노드북 스터디: 넘파이 문제풀이

## 문제 1번
> 일본에는 한식 열풍이 불고 있습니다. 기회를 엿본 영훈이는 대기업을 퇴사하고 신주쿠에 프랜차이즈 ‘품생사닭갈비’ 가맹점을 냈습니다. 그러나 보수적인 아버지께서는 번듯한 직장을 박차고 나온 영훈이가 못마땅합니다. 아버지를 안심시키기 위해 매달 매출을 보고하려고 하는데요.
> 

문제) 엔화(¥)로 저장한 매출 데이터를 원화(₩)로 변환하는 작업이 필요합니다. numpy를 이용하여 엔화 매출이 담겨 있는 파이썬 리스트가 주어졌습니다. 1엔에 10.38원이라고 가정하고, 원화 매출이 담긴 numpy array를 만들어 출력해주세요. (문제 데이터를 활용해주세요.)

In [1]:
import numpy as np

# revenue_in_yen : 엔화(¥) 매출 데이터
revenue_in_yen = [
    300000, 340000, 320000, 360000,
    440000, 140000, 180000, 340000,
    330000, 290000, 280000, 380000,
    170000, 140000, 230000, 390000,
    400000, 350000, 380000, 380000,
    340000, 420000, 150000, 130000,
    360000, 320000, 250000
]

In [4]:
# 엔화 np리스트
yen_array = np.array(revenue_in_yen)

# 원화 np리스트
won_array = yen_array * 10.38

print(yen_array)
print(won_array)

[300000 340000 320000 360000 440000 140000 180000 340000 330000 290000
 280000 380000 170000 140000 230000 390000 400000 350000 380000 380000
 340000 420000 150000 130000 360000 320000 250000]
[3114000. 3529200. 3321600. 3736800. 4567200. 1453200. 1868400. 3529200.
 3425400. 3010200. 2906400. 3944400. 1764600. 1453200. 2387400. 4048200.
 4152000. 3633000. 3944400. 3944400. 3529200. 4359600. 1557000. 1349400.
 3736800. 3321600. 2595000.]


## 문제 2번

> 영훈이에 이어 소문을 들은 Jimmy가 이에 질세라 신주쿠에 품새사닭갈비 집을 차리는데요. 이제 직장인들에게 소문난 맛집입니다. 그러나 매일 성공적인 것은 아닌데요. 목표 일 매출을 달성하지 못하는 날들이 아직 꽤 있었습니다.
> 

문제) 성공적이지 않은 날의 매출만 골라서 보고 싶습니다. 20만 엔 이하의 매출만 담긴 numpy array를 출력해주세요. (문제 데이터를 활용해주세요.)

In [5]:
import numpy as np

# revenue_in_yen : 엔화(¥) 매출 데이터
revenue_in_yen = [
    300000, 340000, 320000, 360000,
    440000, 140000, 180000, 340000,
    330000, 290000, 280000, 380000,
    170000, 140000, 230000, 390000,
    400000, 350000, 380000, 380000,
    340000, 420000, 150000, 130000,
    360000, 320000, 250000
]

In [25]:
# en_array : 엔화(¥) 리스트 array로 변환하기
en_array = np.array(revenue_in_yen)
fillter = np.where(en_array <= 200000)
bad_days = en_array[fillter]
print(bad_days)

[140000 180000 170000 140000 150000 130000]


In [27]:
# 위 단계를 더 간단하게 만드는 마법의 코드~
en_array[np.where(en_array <= 200000)]

array([140000, 180000, 170000, 140000, 150000, 130000])

## 문제 3번

값이 10~49인 벡터를 만들어보세요.

> 문제풀이 tip) np.arange()를 활용하자.
>

In [14]:
Z1 = np.arange(10,49)
print(Z1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


## 문제 4번

1부터 9까지의 값을 활용하여 3행 3열 행렬을 만들어보세요.

> 문제풀이 tip) np.reshape()를 활용하자.
>

In [32]:
Z2 = np.arange(9).reshape(3,3)
print(Z2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 문제 5번

크기가 50인 랜덤 벡터를 만들고 평균값을 찾아보세요.

> 문제풀이 tip1) np.random()을 사용해보자.
> 

> 문제풀이 tip2) np.mean()을 사용해보자.
>

In [34]:
Z3 = np.random.random(50).mean()
print(Z3)

0.510723986915646


## 문제 6번

크기가 7인 랜덤 벡터를 만들어 정렬해보세요.

> 문제풀이 tip) np.sort()를 활용하자.
>

In [40]:
Z4 = np.random.random(7)
Z4.sort()
print(Z4)

[0.05103473 0.15814613 0.48486082 0.70170493 0.729138   0.81225707
 0.91291256]


## 문제 7번

크기가 15인 랜덤 벡터를 만들고 최대값을 0으로 바꾸어보세요.

> 문제풀이 tip) np.argmax()를 활용하자.
>

In [46]:
Z5 = np.random.random(15)
Z5[Z5.argmax()] = 0
print(Z5)

[0.62133706 0.81535625 0.08298681 0.69292087 0.01884205 0.10586
 0.85887217 0.31764208 0.06376389 0.         0.14235291 0.3631674
 0.577328   0.84936279 0.84406372]


## 문제 8번

1부터 25까지의 원소를 갖는 5X5 행렬을 만들고, 임의의 두 행을 서로 바꾸어보세요.

> 문제풀이 tip) 행렬 A에 대해 A[[a, b]] = A[[b, a]] 할 수 있다.
>

In [54]:
A = np.arange(1, 26).reshape(5,5)
B = A.T
print(A)
print(B)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]


## 문제 9번

X행렬이 다음과 같을 때, 행렬 인덱싱을 사용하여 4의 배수만을 선택하여 하나의 벡터로 만드는 NumPy 코드를 작성하세요. (단, NumPy 슬라이싱 인덱싱을 사용하지 말 것!)

In [56]:
X = np.array([[1, 1, 1, 1], [1, 2, 4, 8], [1, 3, 5, 7], [1, 4, 16, 32], [1, 5, 9, 13]])
X

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  5,  7],
       [ 1,  4, 16, 32],
       [ 1,  5,  9, 13]])

In [67]:
# 방법1
for i in X:
    for j in X:
        a = np.where(X%4 == 0)
print(X[a])

[ 4  8  4 16 32]


In [65]:
# 방법2
print(X[np.where(X % 4 ==0)])

[ 4  8  4 16 32]


In [68]:
# 방법3
X[X%4==0]

array([ 4,  8,  4, 16, 32])

## 문제 10번

다음 행렬 X가 5명의 학생이 3번 시험 본 성적이라고 가정했을 때, 각 학생의 최고 성적을 구하는 코드를 작성하세요.

> 문제풀이 tip) 행렬 축(axis) 개념을 인지하고 있다면 수월하게 풀 수 있다.
>

In [69]:
np.random.seed(0)
X = np.random.randint(0, 100, (5,3))
X

array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88],
       [88, 12, 58]])

In [75]:
print(X.max(axis = 1))

[64 67 83 88 88]
